chat/urls.py
from django.urls import include, path
from chat.views import (CreateChatSessionView, ChattingView, PendingChatSessionListView,
                        ActivateChatSessionView, SendMessage, GetUserMessage,
                        CheckActivity, DeleteChatSessionView)

app_name ='chat'
urlpatterns = [
    path('create-chat/', CreateChatSessionView, name='createchatsession'),
    path('chatting/<int:pk>/', ChattingView, name='chatting'),
    path('pending-chats/', PendingChatSessionListView, name='pendingchatsessionlist'),
    path('activate-chat/<int:pk>/', ActivateChatSessionView, name='activatechat'),
    path('send-message/<int:pk>/', SendMessage, name='sendmessage'),
    path('get-user-message/<int:pk>/', GetUserMessage, name='getusermessage'),
    path('check-activity/<int:pk>/', CheckActivity, name='checkactivity'),
    path('delete-session/<int:pk>/', DeleteChatSessionView, name='deletechatsession'),

]

cooperation/urls.py
from django.urls import include, path
from cooperation.views import (CreateJobOpportunityView,JobOpportunityListView,
                                JobOpportunityListViewSuperUser, JobOpportunityDeleteView,
                                CreateApplicationView, ApplicationListView, CreateDelegationRequestView,
                                DelegationRequestListView, CreateRepairManRequestView, RepairManRequestListView,
                                RepairManRequestDeleteView, DelegationRequestDeleteView, ApplicationDeleteView,
                                RepairManRequestCheckView, DelegationRequestCheckView, ApplicationCheckView)

app_name ='cooperation'
urlpatterns = [
    path('create-job-opportunity/',CreateJobOpportunityView, name = 'createjobopportunity'),
    path('job-opportunity-list/',JobOpportunityListView, name = 'jobopportunitylist'),
    path('job-opportunity-list-superuser/',JobOpportunityListViewSuperUser , name = 'jobopportunitylistsuperuser'),
    path('job-opportunity-delete/<int:pk>/',JobOpportunityDeleteView , name = 'jobopportunitydelete'),
    path('apply/<int:pk>/',CreateApplicationView , name = 'createapplicatoin'),
    path('create-delegation-request/',CreateDelegationRequestView , name = 'createdelegationrequest'),
    path('applications-list/',ApplicationListView , name = 'applicationlist'),
    path('delegation-request-list/',DelegationRequestListView , name = 'delegationrequestlist'),
    path('create-repairman-request/',CreateRepairManRequestView , name = 'createrepairmanrequest'),
    path('repairman-request-list/',RepairManRequestListView , name = 'repairmanrequestlist'),
    path('repairman-request-delete/<int:pk>/',RepairManRequestDeleteView , name = 'repairmanrequestdelete'),
    path('delegation-request-delete/<int:pk>/',DelegationRequestDeleteView , name = 'delegationrequestdelete'),
    path('application-delete/<int:pk>/',ApplicationDeleteView , name = 'applicationdelete'),

    path('application-check/<int:pk>/',ApplicationCheckView , name = 'applicationcheck'),
    path('delegation-request-check/<int:pk>/',DelegationRequestCheckView , name = 'delegationrequestcheck'),
    path('repairman-request-check/<int:pk>/',RepairManRequestCheckView , name = 'repairmanrequestcheck'),

]

cooperation/models.py
from django.db import models
from django.utils import timezone

class JobOpportunityModel(models.Model):
    job_title = models.CharField(max_length = 264, blank = False, null = False)
    required_skills = models.TextField(null = False, blank = False)
    descriprion = models.TextField(null = False, blank = False)


class ApplicationModel(models.Model):
    job = models.ForeignKey(JobOpportunityModel, on_delete = models.CASCADE,
                                null = False, blank = False, related_name = 'applications')
    name = models.CharField(max_length = 264, blank = False, null = False)
    checked_at = models.DateTimeField(null = True, blank = True)
    last_name = models.CharField(max_length = 264, blank = False, null = False)
    email = models.EmailField(blank = False, null = False)
    id_number = models.CharField(max_length = 264, blank = False, null = False)
    age = models.CharField(max_length = 264, blank = False, null = False)
    is_man = models.BooleanField(default = True)
    is_single = models.BooleanField(default = True)
    phone_number = models.CharField(max_length = 264, blank = False, null = False)
    cellphone_number = models.CharField(max_length = 264, blank = False, null = False)
    address = models.TextField(null = False, blank = False)

    college_evidence = models.CharField(max_length = 264, blank = True, null = True)
    field_of_study = models.CharField(max_length = 264, blank = True, null = True)
    college_score = models.CharField(max_length = 264, blank = True, null = True)
    name_of_college = models.CharField(max_length = 264, blank = True, null = True)
    english_mastery = models.CharField(max_length = 264, blank = True, null = True)
    computer_mastery = models.CharField(max_length = 264, blank = True, null = True)
    job_attendance = models.CharField(max_length = 264, blank = True, null = True)
    descriprion = models.TextField(null = True, blank = True)
    created_at = models.DateTimeField(default=timezone.now)
    resome = models.FileField(upload_to='resome/',null = True, blank = True, default = r'cataloges/default/default.jpeg')



class DelegationRequestModel(models.Model):
    name = models.CharField(max_length = 264, blank = False, null = False)
    last_name = models.CharField(max_length = 264, blank = False, null = False)
    checked_at = models.DateTimeField(null = True, blank = True)
    email = models.EmailField(blank = False, null = False)
    age = models.CharField(max_length = 264,blank = False, null = False)
    province = models.CharField(max_length = 264, blank = False, null = False)
    city = models.CharField(max_length = 264, blank = False, null = False)
    phone_number = models.CharField(max_length = 264, blank = False, null = False)
    cellphone_number = models.CharField(max_length = 264, blank = False, null = False)
    address = models.TextField(null = False, blank = False)
    area = models.IntegerField(blank = False, null = False)
    for_towerdryer = models.BooleanField(default = False)
    for_package = models.BooleanField(default = False)
    for_radiator = models.BooleanField(default = False)
    for_waterheater = models.BooleanField(default = False)
    has_reservoir = models.BooleanField(default = False)
    created_at = models.DateTimeField(default=timezone.now)

    fax_number = models.CharField(max_length = 264, blank = True, null = True)
    sell_prediction_towerdryer = models.CharField(max_length = 264, blank = True, null = True)
    sell_prediction_package = models.CharField(max_length = 264, blank = True, null = True)
    sell_prediction_radiator = models.CharField(max_length = 264, blank = True, null = True)
    sell_prediction_waterheater = models.CharField(max_length = 264, blank = True, null = True)
    attendance = models.CharField(max_length = 264, blank = True, null = True)
    description = models.TextField(null = True, blank = True)
    ownership_type = models.CharField(max_length = 264, blank = True, null = True)


class RepairManRequestModel(models.Model):
    name = models.CharField(max_length = 264, blank = False, null = False)
    checked_at = models.DateTimeField(null = True, blank = True)
    last_name = models.CharField(max_length = 264, blank = False, null = False)
    age = models.CharField(max_length = 264, blank = False, null = False)
    province = models.CharField(max_length = 264, blank = False, null = False)
    city = models.CharField(max_length = 264, blank = False, null = False)
    is_single = models.BooleanField(default = True)
    phone_number = models.CharField(max_length = 264, blank = False, null = False)
    cellphone_number = models.CharField(max_length = 264, blank = False, null = False)
    address = models.TextField(null = False, blank = False)
    for_towerdryer = models.BooleanField(default = False)
    for_package = models.BooleanField(default = False)
    for_radiator = models.BooleanField(default = False)
    for_waterheater = models.BooleanField(default = False)
    created_at = models.DateTimeField(default=timezone.now)

    college_evidence = models.CharField(max_length = 264, blank = True, null = True)
    field_of_study = models.CharField(max_length = 264, blank = True, null = True)
    college_score = models.CharField(max_length = 264, blank = True, null = True)
    name_of_college = models.CharField(max_length = 264, blank = True, null = True)
    has_office = models.BooleanField(default = False)
    can_travel = models.BooleanField(default = False)
    attendance = models.TextField(null = True, blank = True)
    experience = models.TextField(null = True, blank = True)
    certificates = models.TextField(null = True, blank = True)
    description = models.TextField(null = True, blank = True)

cooperation/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView, TemplateView
from django.forms import modelformset_factory
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.core.paginator import Paginator
from django.shortcuts import get_list_or_404

#handmade
from cooperation.models import JobOpportunityModel, ApplicationModel, DelegationRequestModel, RepairManRequestModel
from cooperation.forms import JobOpportunityForm, ApplicationForm, DelegationRequestForm, RepairManRequestForm
from accounts.decorators import superuser_required


@login_required
@superuser_required
def CreateJobOpportunityView(request):
    if request.method == 'POST':
        job_opportunity_form = JobOpportunityForm(data = request.POST)
        if job_opportunity_form.is_valid():
             job_opportunity = job_opportunity_form.save(commit=False)
             job_opportunity.save()
             return HttpResponseRedirect(reverse('accounts:superuserdashboard'))
        else:
            print(job_opportunity_form.errors)
    else:
        job_opportunity_form = JobOpportunityForm()
    return render(request,'cooperation/createjobopportunity.html',
                  {'job_opportunity_form':job_opportunity_form})



def JobOpportunityListView(request):
    try:
        job_opportunity_list = get_list_or_404(JobOpportunityModel.objects.all())
        return render(request,'cooperation/jobopportunitylist.html',
                      {'job_opportunity_list':job_opportunity_list})
    except:
        return render(request,'cooperation/jobopportunitylist.html')


@login_required
@superuser_required
def JobOpportunityListViewSuperUser(request):
    try:
        job_opportunity_list = get_list_or_404(JobOpportunityModel.objects.all())
        return render(request,'cooperation/jobopportunitylistsuperuser.html',
                      {'job_opportunity_list':job_opportunity_list})
    except:
        return render(request,'cooperation/jobopportunitylistsuperuser.html')


@login_required
@superuser_required
def JobOpportunityDeleteView(request, pk):
    job_opportunity = get_object_or_404(JobOpportunityModel, pk = pk)
    job_opportunity.delete()
    return HttpResponseRedirect(reverse('cooperation:jobopportunitylistsuperuser'))


def CreateApplicationView(request,pk):
    job = get_object_or_404(JobOpportunityModel, pk= pk)
    if request.method == 'POST':
        application_form = ApplicationForm(data = request.POST)
        if application_form.is_valid():
             application = application_form.save(commit=False)
             application.job = job
             if 'resome' in request.FILES:
                application.resome = request.FILES['resome']
             application.save()
             return HttpResponseRedirect(reverse('cooperation:jobopportunitylist'))
        else:
            print(application_form.errors)
    else:
        application_form = ApplicationForm()
    return render(request,'cooperation/createapplication.html',
                  {'application_form':application_form})


@login_required
@superuser_required
def ApplicationListView(request):
    try:
        application_list = get_list_or_404(ApplicationModel.objects.all().order_by('checked_at'))
        return render(request,'cooperation/applicationlist.html',
                      {'application_list':application_list})
    except:
        return render(request,'cooperation/applicationlist.html')


@login_required
@superuser_required
def ApplicationDeleteView(request, pk):
    application = get_object_or_404(ApplicationModel, pk = pk)
    application.delete()
    return HttpResponseRedirect(reverse('cooperation:applicationlist'))


@login_required
@superuser_required
def ApplicationCheckView(request, pk):
    application = get_object_or_404(ApplicationModel, pk = pk)
    if application.checked_at:
        pass
    else:
        application.checked_at = timezone.now()
    application.save()
    return HttpResponseRedirect(reverse('cooperation:applicationlist'))



def CreateDelegationRequestView(request):
    if request.method == 'POST':
        delegation_request_form = DelegationRequestForm(data = request.POST)
        if delegation_request_form.is_valid():
             delegation_request = delegation_request_form.save(commit=False)
             delegation_request.save()
             return HttpResponseRedirect(reverse('home'))
        else:
            print(delegation_request_form.errors)
    else:
        delegation_request_form = DelegationRequestForm()
    return render(request,'cooperation/createdelegationrequest.html',
                  {'delegation_request_form':delegation_request_form})


@login_required
@superuser_required
def DelegationRequestListView(request):
    try:
        delegation_request_list = get_list_or_404(DelegationRequestModel.objects.all().order_by('checked_at'))
        return render(request,'cooperation/delegationrequestlist.html',
                      {'delegation_request_list':delegation_request_list})
    except:
        return render(request,'cooperation/delegationrequestlist.html')


@login_required
@superuser_required
def DelegationRequestDeleteView(request, pk):
    delegation_request = get_object_or_404(DelegationRequestModel, pk = pk)
    delegation_request.delete()
    return HttpResponseRedirect(reverse('cooperation:delegationrequestlist'))


@login_required
@superuser_required
def DelegationRequestCheckView(request, pk):
    delegation_request = get_object_or_404(DelegationRequestModel, pk = pk)
    if delegation_request.checked_at:
        pass
    else:
        delegation_request.checked_at = timezone.now()
    delegation_request.save()
    return HttpResponseRedirect(reverse('cooperation:delegationrequestlist'))


def CreateRepairManRequestView(request):
    if request.method == 'POST':
        repairman_request_form = RepairManRequestForm(data = request.POST)
        if repairman_request_form.is_valid():
             repairman_request = repairman_request_form.save(commit=False)
             repairman_request.saDeleteve()
             return HttpResponseRedirect(reverse('home'))
        else:
            print(repairman_request_form.errors)
    else:
        repairman_request_form = RepairManRequestForm()
    return render(request,'cooperation/createrepairmanrequest.html',
                  {'repairman_request_form':repairman_request_form})


@login_required
@superuser_required
def RepairManRequestListView(request):
    try:
        repairman_request_list = get_list_or_404(RepairManRequestModel.objects.all().order_by('checked_at'))
        return render(request,'cooperation/repairmanrequestlist.html',
                      {'repairman_request_list':repairman_request_list})
    except:
        return render(request,'cooperation/repairmanrequestlist.html')


@login_required
@superuser_required
def RepairManRequestDeleteView(request, pk):
    repairman_request = get_object_or_404(RepairManRequestModel, pk = pk)
    repairman_request.delete()
    return HttpResponseRedirect(reverse('cooperation:repairmanrequestlist'))


@login_required
@superuser_required
def RepairManRequestCheckView(request, pk):
    repairman_request = get_object_or_404(RepairManRequestModel, pk = pk)
    if repairman_request.checked_at:
        pass
    else:
        repairman_request.checked_at = timezone.now()
    repairman_request.save()
    return HttpResponseRedirect(reverse('cooperation:repairmanrequestlist'))

cooperation/templates/cooperation/applicationlist.html
{% extends "BaseTemplates/base1.html" %}

{% block head_block %}
<meta name=”robots” content=”noindex,follow”>
<title>
درخواست های همکاری | شعله خیز آذر
</title>
{% endblock %}

{% block body_block %}
<br>
<h1  class="redC-text uk-card-title uk-text-center fHarmattan uk-text-large">درخواست های همکاری</h1>
<div style="padding:5%" class="uk-grid-match uk-text-center uk-grid-large" uk-grid>
{% if application_list %}
{% for application in application_list %}

      <div class="uk-width-1-1 uk-block">
<div  class="uk-card uk-card-default uk-card-body milkywhiteC">

      <div style="margin-top:-25px; font-size:20px;"  class=" fHarmattan uk-text-large uk-grid-small" uk-grid>
          <div class="uk-width-1-2 uk-width-1-6@m uk-text-left redC-text" >عنوان فرصت شغلی</div><div class="uk-width-1-2 uk-width-1-6@m uk-text-right darkgreyC-text">{{application.job.job_title}}</div>
          <div class="uk-width-1-2 uk-width-1-6@m uk-text-left redC-text" >نام</div><div class="uk-width-1-2 uk-width-1-6@m uk-text-right darkgreyC-text">{{application.name }}</div>
          <div class="uk-width-1-2 uk-width-1-6@m uk-text-left redC-text" >نام خانوادگی</div><div class="uk-width-1-2 uk-width-1-6@m uk-text-right darkgreyC-text">{{application.last_name }}</div>
          <div class="uk-width-1-2 uk-width-1-6@m uk-text-left redC-text" >ایمیل</div><div class="uk-width-1-2 uk-width-1-6@m uk-text-right darkgreyC-text">{{application.email }}</div>
          <div class="uk-width-1-2 uk-width-1-6@m uk-text-left redC-text" >شماره ملی</div><div class="uk-width-1-2 uk-width-1-6@m uk-text-right darkgreyC-text">{{application.id_number }}</div>
          <div class="uk-width-1-2 uk-width-1-6@m uk-text-left redC-text" >سن</div><div class="uk-width-1-2 uk-width-1-6@m uk-text-right darkgreyC-text">{{application.age }}</div>
          <div class="uk-width-1-2 uk-width-1-6@m uk-text-left redC-text" >شماره تماس ثابت</div><div class="uk-width-1-2 uk-width-1-6@m uk-text-right darkgreyC-text">{{application.phone_number }}</div>
          <div class="uk-width-1-2 uk-width-1-6@m uk-text-left redC-text" >شماره همراه</div><div class="uk-width-1-2 uk-width-1-6@m uk-text-right darkgreyC-text">{{application.cellphone_number }}</div>
          <div class="uk-width-1-2 uk-width-1-6@m uk-text-left redC-text" >جنسیت</div><div class="uk-width-1-2 uk-width-1-6@m uk-text-right darkgreyC-text">{% if application.is_man %}آقا{% else %}خانم{% endif %}</div>
          <div class="uk-width-1-2 uk-width-1-6@m uk-text-left redC-text" >وضعیت تاهل</div><div class="uk-width-1-2 uk-width-1-6@m uk-text-right darkgreyC-text">{% if application.is_single %}مجرد{% else %}متاهل{% endif %}</div>
          <div class="uk-width-1-2 uk-width-1-6@m uk-text-left redC-text" >آدرس</div><div class="uk-width-1-2 uk-width-1-6@m uk-text-right darkgreyC-text">{{application.address }}</div>
          <div class="uk-width-1-2 uk-width-1-6@m uk-text-left redC-text" >تاریخ درخواست</div><div class="uk-width-1-2 uk-width-1-6@m uk-text-right darkgreyC-text">{{application.created_at }}</div>
          <div class="uk-width-1-2 uk-width-1-6@m uk-text-left redC-text" >مدرک تحصیلی</div><div class="uk-width-1-2 uk-width-1-6@m uk-text-right darkgreyC-text">{{application.college_evidence }}</div>
          <div class="uk-width-1-2 uk-width-1-6@m uk-text-left redC-text" >رشته تحصیلی</div><div class="uk-width-1-2 uk-width-1-6@m uk-text-right darkgreyC-text">{{application.field_of_study }}</div>
          <div class="uk-width-1-2 uk-width-1-6@m uk-text-left redC-text" >نمره تحصیلی</div><div class="uk-width-1-2 uk-width-1-6@m uk-text-right darkgreyC-text">{{application.college_score }}</div>
          <div class="uk-width-1-2 uk-width-1-6@m uk-text-left redC-text" >نام محل تحصیل</div><div class="uk-width-1-2 uk-width-1-6@m uk-text-right darkgreyC-text">{{application.name_of_college }}</div>
          <div class="uk-width-1-2 uk-width-1-6@m uk-text-left redC-text" >تسلط بر انگلیسی</div><div class="uk-width-1-2 uk-width-1-6@m uk-text-right darkgreyC-text">{{application.english_mastery }}</div>
          <div class="uk-width-1-2 uk-width-1-6@m uk-text-left redC-text" >تسلط بر کامپیوتر</div><div class="uk-width-1-2 uk-width-1-6@m uk-text-right darkgreyC-text">{{application.computer_mastery }}</div>
          <div class="uk-width-1-2 uk-width-1-6@m uk-text-left redC-text" >فایل رزومه</div><div class="uk-width-1-2 uk-width-1-6@m uk-text-right darkgreyC-text">{% if application.resome %}<a href="{{application.resome.url}}">دانلود فایل</a>{% endif %}</div>
          <div class="uk-width-1-1">
          </div>
          <div class="uk-width-1-2 uk-text-left redC-text" >سوابق کاری</div><div class="uk-width-1-2 uk-text-right darkgreyC-text">{{application.job_attendance }}</div>
          <div class="uk-width-1-2 uk-text-left redC-text" >توضیحات دیگر</div><div class="uk-width-1-2 uk-text-right darkgreyC-text">{{application.descriprion }}</div>
          {% if application.checked_at %}
          <div class="uk-width-1-2 uk-text-left redC-text" >تاریخ چک کردن</div><div class="uk-width-1-2 uk-text-right darkgreyC-text">{{application.checked_at }}</div>
          {% else %}
<a href="{% url 'cooperation:applicationcheck' application.pk %}" class="uk-button redC whiteC-text uk-width-1-1 uk-margin-small-bottom fHarmattan uk-text-large">این آگهی را چک کردم</a><br><br>
          {% endif %}
<a href="{% url 'cooperation:applicationdelete' application.pk %}" class="uk-button redC whiteC-text uk-width-1-1 uk-margin-small-bottom fHarmattan uk-text-large">حذف</a>
<br>
      </div>
</div>

</div>

{% endfor %}
{% else %}
<div class="uk-width-1-1 uk-block">
<div  class="uk-card uk-card-default uk-card-body milkywhiteC">

<div style="margin-top:-25px"  class=" fHarmattan uk-text-large uk-grid-small" uk-grid>
    <div class="uk-width-1- uk-text-center redC-text" >فعلا هیچ درخواست همکاری وجود ندارد.
<br>
با تشکر از همکاری شما
<br>
شعله خیز آذر.
    </div>


</div>



</div>

</div>
{% endif %}
</div>
    {% endblock %}

cooperation/templates/cooperation/jobopportunitylist.html
{% extends "BaseTemplates/base1.html" %}

{% block head_block %}
<meta name=”robots” content=”noindex,follow”>
<title>
فرصت های شغلی | شعله خیز آذر
</title>
{% endblock %}

{% block body_block %}
<div style="padding:5%" >

<h1 class="redC-text fYekan-bold uk-text-right fHarmattan font-6">فرصت های شغلی</h1>
<br>
<div class="uk-grid-match uk-text-center uk-grid-large" uk-grid>
{% if job_opportunity_list %}
{% for job_opportunity in job_opportunity_list %}

      <div class="uk-width-1-1 uk-block">
<div  class="uk-card uk-card-default uk-card-body milkywhiteC border-radius-2 shadow-3">

      <div style="margin-top:-25px; font-size:18px;"  class=" fHarmattan uk-text-large uk-grid-small" uk-grid>
          <div class="uk-width-1-1 uk-text-center redC-text" >{{job_opportunity.job_title}}</div>

          <div class="uk-width-1-4 uk-text-left redC-text" >مهارت های مورد نیاز</div><div class="uk-width-3-4 uk-text-right darkgreyC-text">{{job_opportunity.required_skills|linebreaks }}</div>
          <div class="uk-width-1-4 uk-text-left redC-text" >توضیحات فرصت شغلی</div><div class="uk-width-3-4 uk-text-right darkgreyC-text">{{job_opportunity.descriprion|linebreaks }}</div>

<a style="font-size:18px;padding-top:10px;padding-bottom:10px;" href="{% url 'cooperation:createapplicatoin' job_opportunity.pk %}" class="uk-button redC uk-width-1-1 uk-margin-small-bottom whiteC-text fYekan-bold border-radius-2">درخواست همکاری</a>
<br>

      </div>



</div>

</div>

{% endfor %}
{% else %}
<div class="uk-width-1-1 uk-block">
<div  class="uk-card uk-card-default uk-card-body milkywhiteC">

<div style="margin-top:-25px"  class=" fHarmattan uk-text-large uk-grid-small" uk-grid>
    <div class="uk-width-1- uk-text-center redC-text" >فعلا هیچ فرصت شغلی برای شرکت شعله خیز آذر وجود ندارد
<br>
با تشکر از همکاری شما
<br>
شعله خیز آذر.
    </div>


</div>



</div>

</div>
{% endif %}
</div>

</div>
    {% endblock %}

cooperation/templates/cooperation/jobopportunitylistsuperuser.html
{% extends "BaseTemplates/base1.html" %}

{% block head_block %}
<meta name=”robots” content=”noindex,follow”>
<title>
فرصت های شغلی | شعله خیز آذر
</title>
{% endblock %}

{% block body_block %}
<br>
<h3 style="font-size:30px;" class="redC-text uk-card-title uk-text-center fHarmattan uk-text-large">فرصت های شغلی</h3>
<div style="padding:5%" class="uk-grid-match uk-text-center uk-grid-large" uk-grid>
{% if job_opportunity_list %}
{% for job_opportunity in job_opportunity_list %}

      <div class="uk-width-1-1 uk-block">
<div  class="uk-card uk-card-default uk-card-body milkywhiteC">

      <div style="margin-top:-25px"  class=" fHarmattan uk-text-large uk-grid-small" uk-grid>
          <div class="uk-width-1-2 uk-text-left redC-text" >عنوان فرصت شغلی</div><div class="uk-width-1-2 uk-text-right darkgreyC-text">{{job_opportunity.job_title}}</div>

          <div class="uk-width-1-4 uk-text-left redC-text" >مهارت های مورد نیاز</div><div class="uk-width-3-4 uk-text-right darkgreyC-text">{{job_opportunity.required_skills|linebreaks }}</div>
          <div class="uk-width-1-4 uk-text-left redC-text" >توضیحات فرصت شغلی</div><div class="uk-width-3-4 uk-text-right darkgreyC-text">{{job_opportunity.descriprion|linebreaks }}</div>

<a href="{% url 'cooperation:jobopportunitydelete' job_opportunity.pk  %}" class="uk-button redC uk-width-1-1 uk-margin-small-bottom whiteC-text fHarmattan uk-text-large">حذف</a>
<br>

      </div>



</div>

</div>

{% endfor %}
{% else %}
<div class="uk-width-1-1 uk-block">
<div  class="uk-card uk-card-default uk-card-body milkywhiteC">

<div style="margin-top:-25px"  class=" fHarmattan uk-text-large uk-grid-small" uk-grid>
    <div class="uk-width-1- uk-text-center redC-text" >فعلا هیچ فرصت شغلی برای شرکت شعله خیز آذر آذر وجود ندارد
<br>
با تشکر از همکاری شما
<br>
شعله خیز آذر.
    </div>


</div>



</div>

</div>
{% endif %}
</div>
    {% endblock %}