accounts/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from accounts.forms import UserLoginForm

# handmade
from accounts.views import SuperUserDashboardView, ForgotPasswordView, PasswordChangeView

app_name ='accounts'
urlpatterns = [
    path('auth/',auth_views.LoginView.as_view(template_name='registration/login.html',authentication_form=UserLoginForm), name='login'),
    path('dashboard/',SuperUserDashboardView, name='superuserdashboard'),
    path('forgot-password/',ForgotPasswordView, name='passwordforget'),
    path('change-password/<slug:slug>/',PasswordChangeView, name='passwordchange'),

]

chat/urls.py
from django.urls import include, path
from chat.views import (CreateChatSessionView, ChattingView, PendingChatSessionListView,
                        ActivateChatSessionView, SendMessage, GetUserMessage,
                        CheckActivity, DeleteChatSessionView)

app_name ='chat'
urlpatterns = [
    path('create-chat/', CreateChatSessionView, name='createchatsession'),
    path('chatting/<int:pk>/', ChattingView, name='chatting'),
    path('pending-chats/', PendingChatSessionListView, name='pendingchatsessionlist'),
    path('activate-chat/<int:pk>/', ActivateChatSessionView, name='activatechat'),
    path('send-message/<int:pk>/', SendMessage, name='sendmessage'),
    path('get-user-message/<int:pk>/', GetUserMessage, name='getusermessage'),
    path('check-activity/<int:pk>/', CheckActivity, name='checkactivity'),
    path('delete-session/<int:pk>/', DeleteChatSessionView, name='deletechatsession'),

]

company/urls.py
from django.urls import include, path
from company.views import (ContactUsView, AboutUsView, ContactUsListView,
                            ContactUsDeleteView, ComplaintView, ComplaintDeleteView,
                            ComplaintListView, CreateFeedbackView, FeedbackListView,
                            FeedbackDeleteView)

app_name ='company'
urlpatterns = [
    path('about-us/',AboutUsView, name = 'about-us'),
    path('contact-us/',ContactUsView, name = 'contact-us'),
    path('create-feedback/',CreateFeedbackView, name = 'createfeedback'),
    path('feedback-list/',FeedbackListView, name = 'feedbacklist'),
    path('complaint/',ComplaintView, name = 'complaint'),
    path('contact-us-list/',ContactUsListView, name = 'contact-us-list'),
    path('complaint-list/',ComplaintListView, name = 'complaint-list'),
    path('contact-us-delete/<int:pk>/',ContactUsDeleteView, name = 'contact-us-delete'),
    path('feedback-delete/<int:pk>/',FeedbackDeleteView, name = 'feedback-delete'),
    path('complaint-delete/<int:pk>/',ComplaintDeleteView, name = 'complaint-delete'),

]

gallery/urls.py
from django.urls import include, path
from gallery.views import (CreatePhotoView, PhotoListView, PhotoDeleteView,
                            PhotoUpdateView, GalleryView, CreateVideoView,
                            VideoListView, VideoDeleteView)

app_name ='gallery'
urlpatterns = [
    path('createphoto/', CreatePhotoView, name='createphoto'),
    path('createvideo/', CreateVideoView, name='createvideo'),
    path('photo-list/', PhotoListView, name='photolist'),
    path('video-list/', VideoListView, name='videolist'),
    path('photo-delete/<int:pk>/', PhotoDeleteView, name='photodelete'),
    path('video-delete/<int:pk>/', VideoDeleteView, name='videodelete'),
    path('photo-update/<int:pk>/', PhotoUpdateView, name='photoupdate'),
    path('gallery/', GalleryView, name='gallery'),

]

order/urls.py
from django.urls import include, path
from order.views import (OrderingView, CheckedOrdersListView, OrdersDetailView,
                        UnCheckedOrdersListView, OrdersChangeStatus, OrderDeleteView)

app_name ='ordering'
urlpatterns = [
    path('ordering/<int:pk>/', OrderingView, name='order'),
    path('checked-list/', CheckedOrdersListView, name='checkedlist'),
    path('unchecked-list/', UnCheckedOrdersListView, name='uncheckedlist'),
    path('detail/<int:pk>/', OrdersDetailView, name='detail'),
    path('change-status/<int:pk>/', OrdersChangeStatus, name='changestatus'),
    path('delete/<int:pk>/', OrderDeleteView, name='orderdelete'),


]

products/urls.py
from django.urls import include, path
from products.views import (CreateProductView, ProductsListViewSuperUser,
                            ProductsDeleteView, ProductsUpdateView,
                            TowerDryerListView, PackageListView,
                            RadiatorListView, WaterHeaterListView)

app_name ='products'
urlpatterns = [
    path('create/', CreateProductView, name='create'),
    path('list-superuser/', ProductsListViewSuperUser, name='listsuperuser'),
    path('delete/<int:pk>/', ProductsDeleteView, name='delete'),
    path('update/<int:pk>/', ProductsUpdateView, name='update'),
    path('towerdryer-list/', TowerDryerListView, name='towerdryerlist'),
    path('package-list/', PackageListView, name='packagelist'),
    path('radiator-list/', RadiatorListView, name='radiatorlist'),
    path('waterheater-list/', WaterHeaterListView, name='waterheaterlist'),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.text import slugify
from django.conf import settings

class UserModel(AbstractUser):
    name = models.CharField(max_length=216, null = False, blank = False)
    is_commonuser = models.BooleanField('CommonUser Status', default = False)
    slug = models.SlugField(unique = True, null = False, blank = False)
    user_logs = models.TextField(default='',null = True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.username)
        super(UserModel, self).save(*args, **kwargs)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from accounts.models import UserModel
from django.core import validators
from django.contrib.auth.forms import AuthenticationForm

class UserForm(UserCreationForm):
    '''form for creating a user'''


    terms = forms.BooleanField(
    error_messages={'required': 'لطفا شرایط و قوانین سایت را مطالعه کرده و تیک موافقت را بزنید'},
    widget=forms.CheckboxInput(attrs={'class': 'uk-checkbox'})
    )

    Hfield = forms.CharField(required=False,widget =forms.HiddenInput, validators=[validators.MaxLengthValidator(0)])

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)

    username = forms.CharField(widget=forms.TextInput(
        attrs={'class':'uk-input fHarmattan','placeholder':'شماره تلفن مثال 9141234567','id':'username','onblur':'checkLength(this)'}))
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={
'class':'uk-input fHarmattan redC-text','placeholder':'رمز عبور'
        }))
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={
'class':'uk-input fHarmattan redC-text','placeholder':'تکرار رمز عبور'
        }))

    class Meta(UserCreationForm):
        model = UserModel
        fields = ('username','email',
                  'name','password1','password2')
        widgets = {
            'username': forms.TextInput(attrs={'class':'uk-input fHarmattan','placeholder':'شماره همراه','id':'username','onblur':'checkLength(this)'},),
            'name': forms.TextInput(attrs={'class':'uk-input fHarmattan','placeholder':'نام و نام خانوادگی'},),
        }


class TypesForm(forms.Form):

    commonusers = forms.BooleanField(required=False)

    Hfield = forms.CharField(required=False,widget =forms.HiddenInput, validators=[validators.MaxLengthValidator(0)])


class UserUpdateForm(forms.ModelForm):
    Hfield = forms.CharField(required=False,widget =forms.HiddenInput, validators=[validators.MaxLengthValidator(0)])

    class Meta():
        model = UserModel
        fields = ('first_name','email','last_name')
        widgets = {
            'email': forms.TextInput(attrs={'id':'email'}),
            'first_name': forms.TextInput(attrs={'id':'first_name'}),
            'last_name': forms.TextInput(attrs={'id':'last_name'}),
        }


class UserLoginForm(AuthenticationForm):
    Hfield = forms.CharField(required=False,widget =forms.HiddenInput, validators=[validators.MaxLengthValidator(0)])


    username = forms.CharField(widget=forms.TextInput(
        attrs={'class':'uk-input fHarmattan redC-text','placeholder':'شماره همراه','id':'username','onblur':'checkLength(this)'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
'class':'uk-input fHarmattan redC-text','placeholder':'رمز عبور'
        }
))
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)


class PasswordChangeForm(forms.Form):
    current_password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'uk-input fHarmattan','placeholder':'رمز فعلی','id':'current_password'}))
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'uk-input fHarmattan','placeholder':'رمز جدید','id':'new_password'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'uk-input fHarmattan','placeholder':'تکرار رمز جدید','id':'confirm_password'}))
    Hfield = forms.CharField(required=False,widget =forms.HiddenInput, validators=[validators.MaxLengthValidator(0)])


class ForgotPasswordForm(forms.Form):
    phone_number = forms.CharField(required = True, widget=forms.TextInput(attrs={'class':'uk-input fHarmattan','placeholder':'مثال 9141234567','id':'username','onblur':'checkLength(this)'}))
    Hfield = forms.CharField(required=False,widget =forms.HiddenInput, validators=[validators.MaxLengthValidator(0)])

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView, TemplateView
from django.forms import modelformset_factory
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.core.paginator import Paginator
from django.shortcuts import get_list_or_404
import jdatetime
import datetime
import random
from django.conf import settings
from django.contrib.auth import authenticate, login
from django.utils import timezone
# handmade

from delegations.forms import DelegationForm
from delegations.models import DelegationModel
from accounts.decorators import superuser_required
from accounts.forms import ForgotPasswordForm, PasswordChangeForm
from accounts.models import UserModel
from commonuser.models import CommonUserModel
from company.utils import SendMessage
from chat.models import ChatSessionModel
from chat.views import DeleteInactiveChats


@login_required
@superuser_required
def SuperUserDashboardView(request):
    DeleteInactiveChats(request)
    active_chats = ChatSessionModel.objects.count()
    return render(request,'accounts/superuserdashboard.html',{'active_chats':active_chats})


def ForgotPasswordView(request):
    try:
        last_retry_str = request.session['last_retry']
        last_retry = datetime.datetime.strptime(last_retry_str,"%Y-%m-%d %H:%M:%S")
    except:
        last_retry = datetime.datetime.now()
    now = datetime.datetime.now()
    if now >= last_retry:
        if request.method == 'POST':
            data = request.POST.copy()
            form = ForgotPasswordForm(data=request.POST)

            phone_number_exists = False
            if form.is_valid():
                phone_number = form.cleaned_data.get('phone_number')
                number = '0'+phone_number

                try :
                    user = get_object_or_404(UserModel,username = phone_number)
                    if user :
                        var = 'abcdefghijkmnpqrstuvwxyzABCDEFJKLMNPQRSTUVWXYZ123456789'
                        new_password=''
                        for i in range(0,random.randrange(7,8,1)):
                            c = random.choice(var)
                            new_password += c

                        text = 'رمز عبور جدید شما در وبسایت شعله خیز: {code}\n شعله خیز آذر'.format(code = new_password)
                        SendMessage(number,text)
                        phone_number_exists = True
                        print(new_password)
                        user.set_password(new_password)
                        user.save()
                        now = datetime.datetime.now() + datetime.timedelta(minutes=3)
                        str_now = str(now.year)+'-'+str(now.month)+'-'+str(now.day)+' '+str(now.hour)+':'+str(now.minute)+':'+str(now.second)
                        request.session['last_retry'] = str_now
                        return HttpResponseRedirect(reverse('accounts:login'))
                except:
                    pass



            else:
                print(form.errors)
            if not phone_number_exists:
                return HttpResponseRedirect(reverse('commonuser:wrongphonenumber'))


        else:
            form = ForgotPasswordForm()
        return render(request,'accounts/forgotpassword.html',{'form':form})
    else:
        return HttpResponseRedirect(reverse('commonuser:wait'))


@login_required
def PasswordChangeView(request,slug):
    user = get_object_or_404(UserModel,slug = slug)
    if request.method == 'POST':
        password_form = PasswordChangeForm(data = request.POST)
        if password_form.is_valid():
            current_password = password_form.cleaned_data.get('current_password')
            logged_in = authenticate(request, username=user.username, password=current_password)

            if logged_in is not None:
                if password_form.cleaned_data.get('new_password') == password_form.cleaned_data.get('confirm_password'):
                    new_password = password_form.cleaned_data.get('new_password')
                    try:
                        user.set_password(new_password)
                        user.save()
                        return HttpResponseRedirect(reverse('accounts:login'))
                    except:
                        error1 ='کلمه عبور باید بیش از 6 کاراکتر باشد'
                        error2 ='کلمه عبور باید نمیتواند شامل نام کاربری باشد'
                        error3 ='کلمه عبور نمیتواند خیلی ساده باشد'
                        return render(request,'accounts/passwordchange.html',{'form':password_form,'error1':error1,'error2':error2,'error3':error3})
                else:
                    error4 = 'رمز های وارد شده با هم مطابقت ندارند'
                    password_form = PasswordChangeForm()
                    return  render(request,'accounts/passwordchange.html',
                                          {'error4':error4,'form':password_form})

            else:
                error4 = 'رمزعبور وارد شده صحیح نیست'
                password_form = PasswordChangeForm()
                return  render(request,'accounts/passwordchange.html',
                                      {'error4':error4,'form':password_form})
    else:
        password_form = PasswordChangeForm()
        return  render(request,'accounts/passwordchange.html',
                              {'form':password_form})

accounts/templates/accounts/forgotpassword.html
{% extends "BaseTemplates/base1.html" %}

{% block head_block %}
<meta name=”robots” content=”noindex,follow”>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<title>
فراموشی رمز عبور | شعله خیز آذر
</title>
{% endblock %}
{% block body_block %}
<br><br>
<div style="padding:6%" class="uk-grid-match uk-text-center uk-grid-large" uk-grid>
  <div class="uk-width-1-1  uk-block">
<div  class="uk-card uk-card-default uk-card-body milkywhiteC">
    <h3 style="font-size:30px;" class="redC-text uk-card-title uk-align-center fHarmattan">فراموشی رمز عبور</h3>
    <form enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      <div class="uk-grid-match uk-grid-small uk-text-center" uk-grid>

      <div class="uk-width-1-1@m redC-text fHarmattan">
    شماره تلفن خود را وارد کنید تا رمز عبور جدید برای شما ارسال شود
      </div>

      <div class="uk-width-1-1@m" >
              <div class="uk-width-2-3">
    {{form.phone_number}}
    </div>
        <div class="uk-width-1-6 redC-text " style="direction:ltr; font-size:18px;padding-top:5px; " >
+98
        </div>
        <div class="uk-width-1-6 goldC-text " style="direction:ltr; font-size:18px;padding-top:5px; " >
          <span id="phonenumbervalidator" class="helper-text" data-error="wrong" data-success="right"></span>

        </div>

      </div>



      {% if form.errors %}
      <div class="uk-width-1-1 fHarmattan darkgreyC-text"><p>
      خطایی رخ داد.
      لطفا فیلد هارا دوباره با دقت پر کنید.<br>
      در صورت تداوم خطا مشکل را به پشتیبانان سایت اطلاع دهید.<br>

      {{form.errors}}</p>
    </div>
      {% endif %}

      </div>
      <br>
<button style='margin-top:20px;' class='uk-button uk-button-primary fHarmattan redC' type='submit'>تایید</button><br><br>
    </form>
</div>

</div>
</div>
<br><br><br>

{% endblock %}


{% block script_block %}
<script type="text/javascript">
  function myFunction() {
  // Get the checkbox
  var checkBox = document.getElementById("myCheck");
  // Get the output text
  var text = document.getElementById("text");

  // If the checkbox is checked, display the output text
  if (checkBox.checked == true){
    text.style.display = "block";
  } else {
    text.style.display = "none";
  }
}
</script>

<script>
  function checkLength(el) {
    if (el.value.length == 10) {
var str = "<i class='right tiny material-icons goldC-text'>done_all</i>";
var result = str.fontcolor("green");
var str2 = "       <button style='margin-top:20px;' class='uk-button uk-button-primary fHarmattan redC' type='submit'>تایید</button>";
var result2 = str2.fontcolor("green");
document.getElementById("phonenumbervalidator").innerHTML = result;
document.getElementById("button").innerHTML = result2;

    }
    if (isNaN(el.value) || el.value.length != 10 && el.value.length !=0) {
var str = "<i class='right tiny material-icons redC-text'>close</i>";
var result = str.fontcolor("red");
document.getElementById("phonenumbervalidator").innerHTML = result;
var str2 = "";
var result2 = str2.fontcolor("green");
document.getElementById("button").innerHTML = result2;

    }


  }
</script>
{% endblock %}

accounts/templates/accounts/passwordchange.html
{% extends "BaseTemplates/base1.html" %}

{% block head_block %}
<meta name=”robots” content=”noindex,follow”>
<title>
تغییر رمز عبور | شعله خیز آذر
</title>
{% endblock %}

{% block body_block %}
<br>
<div style="padding:7%">


<div style="padding: 1%;border-radius: 8px;" uk-grid>
<div class=" uk-width-1-1 uk-block fHarmattan ">
<div class="uk-card uk-card-body milkywhiteC ">
<div class="uk-card uk-card uk-card-body uk-text-center">
    <h1 style="font-size:30px;" class="redC-text uk-card-title uk-align-center fHarmattan">تغییر رمز عبور</h1>
    <form enctype="multipart/form-data" method="POST">
      {% csrf_token %}


      <div  class="uk-grid-match uk-grid-small uk-text-center" uk-grid>

      <div class="uk-width-1-1 uk-width-1-3@m uk-width-1-2@s">
{{form.current_password}}
      </div>

      <div class="uk-width-1-1 uk-width-1-3@m uk-width-1-2@s">
{{form.new_password}}
      </div>

      <div class="uk-width-1-1 uk-width-1-3@m uk-width-1-2@s">
{{form.confirm_password}}
      </div>

    </div>


      <br>
      {% if form.errors %}
      <div class="uk-width-1-1 fHarmattan darkgreyC-text"><p>
      خطایی رخ داد.
      لطفا فیلد هارا دوباره با دقت پر کنید.<br>
      در صورت تداوم خطا مشکل را به پشتیبانان سایت اطلاع دهید.<br>

      {{form.errors}}</p>
    </div>
      {% endif %}

      <button style="margin-top:20px;" class="uk-button uk-button-primary fHarmattan redC " type="submit">تایید
    </button>
    </form>
</div>


</div>
</div>
</div>
</div>
<br><br>

    {% endblock %}

accounts/templates/accounts/superuserdashboard.html
{% extends "BaseTemplates/base1.html" %}

{% block head_block %}
<meta name=”robots” content=”noindex,follow”>
<title>
داشبورد | شعله خیز آذر
</title>
{% endblock %}

{% block body_block %}
<br>
<h1 class="uk-text-center redC-text fHarmattan">داشبورد</h1>
<br><br>
<div class="uk-grid-match uk-grid-small uk-text-center" uk-grid>
      <div style="padding-left:9%;padding-right:10%;" class="uk-width-1-1 ">
        <a href="{% url 'chat:pendingchatsessionlist' %}" class="uk-button redC uk-width-1-1 uk-margin-small-bottom whiteC-text fHarmattan uk-text-large">لیست چت های در انتظار{% if active_chats %}  <span style="border-radius:10px;" class="whiteC-text fHarmattan">:{{active_chats}}</span>{% endif %}</a>
<a href="{% url 'products:create' %}" class="uk-button redC uk-width-1-1 uk-margin-small-bottom whiteC-text fHarmattan uk-text-large">ایجاد محصول</a>
<a href="{% url 'products:listsuperuser' %}" class="uk-button redC uk-width-1-1 uk-margin-small-bottom whiteC-text fHarmattan uk-text-large">محصولات</a>
<a href="{% url 'order:checkedlist' %}" class="uk-button redC uk-width-1-1 uk-margin-small-bottom whiteC-text fHarmattan uk-text-large">سفارشات چک شده</a>
<a href="{% url 'order:uncheckedlist' %}" class="uk-button redC uk-width-1-1 uk-margin-small-bottom whiteC-text fHarmattan uk-text-large">سفارشان چک نشده</a>
<a href="{% url 'gallery:createphoto' %}" class="uk-button redC uk-width-1-1 uk-margin-small-bottom whiteC-text fHarmattan uk-text-large">افزودن عکس به گالری</a>
<a href="{% url 'gallery:createvideo' %}" class="uk-button redC uk-width-1-1 uk-margin-small-bottom whiteC-text fHarmattan uk-text-large">افزودن ویدیو به گالری</a>
<a href="{% url 'gallery:photolist' %}" class="uk-button redC uk-width-1-1 uk-margin-small-bottom whiteC-text fHarmattan uk-text-large">لیست عکس های گالری</a>
<a href="{% url 'gallery:videolist' %}" class="uk-button redC uk-width-1-1 uk-margin-small-bottom whiteC-text fHarmattan uk-text-large">لیست ویدیو های گالری</a>
<a href="{% url 'delegations:add' %}" class="uk-button redC uk-width-1-1 uk-margin-small-bottom whiteC-text fHarmattan uk-text-large">افزودن مرکز خدمات</a>
<a href="{% url 'delegations:listsuperuser' %}" class="uk-button redC uk-width-1-1 uk-margin-small-bottom whiteC-text fHarmattan uk-text-large">لیست مراکز خدماتی</a>
<a href="{% url 'company:contact-us-list' %}" class="uk-button redC uk-width-1-1 uk-margin-small-bottom whiteC-text fHarmattan uk-text-large">لیست تماس با ما</a>
<a href="{% url 'company:complaint-list' %}" class="uk-button redC uk-width-1-1 uk-margin-small-bottom whiteC-text fHarmattan uk-text-large">لیست شکایات</a>
<a href="{% url 'company:feedbacklist' %}" class="uk-button redC uk-width-1-1 uk-margin-small-bottom whiteC-text fHarmattan uk-text-large">لیست نظرسنجی ها</a>
<a href="{% url 'cooperation:createjobopportunity' %}" class="uk-button redC uk-width-1-1 uk-margin-small-bottom whiteC-text fHarmattan uk-text-large">ایجاد فرصت های شغلی</a>
<a href="{% url 'cooperation:jobopportunitylistsuperuser' %}" class="uk-button redC uk-width-1-1 uk-margin-small-bottom whiteC-text fHarmattan uk-text-large">لیست فرصت های شغلی</a>
<a href="{% url 'cooperation:applicationlist' %}" class="uk-button redC uk-width-1-1 uk-margin-small-bottom whiteC-text fHarmattan uk-text-large">لیست درخواست های همکاری</a>
<a href="{% url 'cooperation:delegationrequestlist' %}" class="uk-button redC uk-width-1-1 uk-margin-small-bottom whiteC-text fHarmattan uk-text-large">لیست درخواست های نمایندگی فروش</a>
<a href="{% url 'cooperation:repairmanrequestlist' %}" class="uk-button redC uk-width-1-1 uk-margin-small-bottom whiteC-text fHarmattan uk-text-large">لیست درخواست های نمایندگی خدمات</a>

</div>
<div class="uk-width-1-6 uk-width-1-4@m">

</div>
</div>
<br><br><br><br>
    {% endblock %}