accounts/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from accounts.forms import UserLoginForm

# handmade
from accounts.views import SuperUserDashboardView, ForgotPasswordView, PasswordChangeView

app_name ='accounts'
urlpatterns = [
    path('auth/',auth_views.LoginView.as_view(template_name='registration/login.html',authentication_form=UserLoginForm), name='login'),
    path('dashboard/',SuperUserDashboardView, name='superuserdashboard'),
    path('forgot-password/',ForgotPasswordView, name='passwordforget'),
    path('change-password/<slug:slug>/',PasswordChangeView, name='passwordchange'),

]

chat/urls.py
from django.urls import include, path
from chat.views import (CreateChatSessionView, ChattingView, PendingChatSessionListView,
                        ActivateChatSessionView, SendMessage, GetUserMessage,
                        CheckActivity, DeleteChatSessionView)

app_name ='chat'
urlpatterns = [
    path('create-chat/', CreateChatSessionView, name='createchatsession'),
    path('chatting/<int:pk>/', ChattingView, name='chatting'),
    path('pending-chats/', PendingChatSessionListView, name='pendingchatsessionlist'),
    path('activate-chat/<int:pk>/', ActivateChatSessionView, name='activatechat'),
    path('send-message/<int:pk>/', SendMessage, name='sendmessage'),
    path('get-user-message/<int:pk>/', GetUserMessage, name='getusermessage'),
    path('check-activity/<int:pk>/', CheckActivity, name='checkactivity'),
    path('delete-session/<int:pk>/', DeleteChatSessionView, name='deletechatsession'),

]

company/urls.py
from django.urls import include, path
from company.views import (ContactUsView, AboutUsView, ContactUsListView,
                            ContactUsDeleteView, ComplaintView, ComplaintDeleteView,
                            ComplaintListView, CreateFeedbackView, FeedbackListView,
                            FeedbackDeleteView)

app_name ='company'
urlpatterns = [
    path('about-us/',AboutUsView, name = 'about-us'),
    path('contact-us/',ContactUsView, name = 'contact-us'),
    path('create-feedback/',CreateFeedbackView, name = 'createfeedback'),
    path('feedback-list/',FeedbackListView, name = 'feedbacklist'),
    path('complaint/',ComplaintView, name = 'complaint'),
    path('contact-us-list/',ContactUsListView, name = 'contact-us-list'),
    path('complaint-list/',ComplaintListView, name = 'complaint-list'),
    path('contact-us-delete/<int:pk>/',ContactUsDeleteView, name = 'contact-us-delete'),
    path('feedback-delete/<int:pk>/',FeedbackDeleteView, name = 'feedback-delete'),
    path('complaint-delete/<int:pk>/',ComplaintDeleteView, name = 'complaint-delete'),

]

gallery/urls.py
from django.urls import include, path
from gallery.views import (CreatePhotoView, PhotoListView, PhotoDeleteView,
                            PhotoUpdateView, GalleryView, CreateVideoView,
                            VideoListView, VideoDeleteView)

app_name ='gallery'
urlpatterns = [
    path('createphoto/', CreatePhotoView, name='createphoto'),
    path('createvideo/', CreateVideoView, name='createvideo'),
    path('photo-list/', PhotoListView, name='photolist'),
    path('video-list/', VideoListView, name='videolist'),
    path('photo-delete/<int:pk>/', PhotoDeleteView, name='photodelete'),
    path('video-delete/<int:pk>/', VideoDeleteView, name='videodelete'),
    path('photo-update/<int:pk>/', PhotoUpdateView, name='photoupdate'),
    path('gallery/', GalleryView, name='gallery'),

]

products/urls.py
from django.urls import include, path
from products.views import (CreateProductView, ProductsListViewSuperUser,
                            ProductsDeleteView, ProductsUpdateView,
                            TowerDryerListView, PackageListView,
                            RadiatorListView, WaterHeaterListView)

app_name ='products'
urlpatterns = [
    path('create/', CreateProductView, name='create'),
    path('list-superuser/', ProductsListViewSuperUser, name='listsuperuser'),
    path('delete/<int:pk>/', ProductsDeleteView, name='delete'),
    path('update/<int:pk>/', ProductsUpdateView, name='update'),
    path('towerdryer-list/', TowerDryerListView, name='towerdryerlist'),
    path('package-list/', PackageListView, name='packagelist'),
    path('radiator-list/', RadiatorListView, name='radiatorlist'),
    path('waterheater-list/', WaterHeaterListView, name='waterheaterlist'),

]

templates/BaseTemplates/base1.html
{% load static %}
<!DOCTYPE html>
<html dir="rtl" class="redC" style="overflow-x: hidden;">
  <head>
    {% block head_block %}
    {% endblock %}
    {% load static %}
    <!DOCTYPE html>
        <meta charset="utf-8">
        <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="https://sholehkhiz.com/favicon.png"/>
    <link rel="shortcut icon" type="image/png" href="/media/Logo/logo.png" sizes="16x16"/>
        <link type="text/css" rel="stylesheet" href="{% static 'css/uikit-rtl.css' %}" media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="{% static 'css/styles.css' %}"/>
        <script src="{% static 'js/uikit.min.js' %}" ></script>
        <script src="{% static 'js/uikit-icons.min.js' %}" ></script>
      </head>
      <body style="background-color: #e8e8e8;" class="redC">
        <header>
            <!-- Main Navbar -->
            <nav class="uk-navbar-container uk-margin" style="background-color: #ff0a0a;position: fixed;right: 0;left: 0;top: 0;z-index: 1030;box-shadow: 0 15px 17px rgba(0, 0,0, 0.18);" uk-navbar>
                <div class="uk-navbar-center">
                  <div class="uk-navbar-center-left"><div>
    <ul  class="uk-navbar-nav uk-visible@m">
      <li>
    <a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:20px; " class="  " href="#">محصولات و سفارش</a>
    <div  class="uk-navbar-dropdown " style="margin-top:-10px; background-color:#ff0a0a;">
        <ul class="uk-nav uk-navbar-dropdown-nav">
            <li class="uk-active"><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:20px; " href="{% url 'products:radiatorlist' %}">رادیاتور پنلی</a></li>
            <li class="uk-active"><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:20px; " href="{% url 'products:towerdryerlist' %}">حوله خشک کن</a></li>
            <li class="uk-active"><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:20px; " href="{% url 'products:packagelist' %}">پکیج دیواری</a></li>
            <li class="uk-active"><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:20px; " href="{% url 'products:waterheaterlist' %}">آبگرمکن</a></li>
        </ul>
    </div>
</li>
<li>
<a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:20px; " class="  " href="#">همکاری</a>
<div  class="uk-navbar-dropdown" style="margin-top:-10px; background-color:#ff0a0a;">
  <ul class="uk-nav uk-navbar-dropdown-nav " style="margin:-10%;">
      <li class="uk-active"><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:16px; " href="{% url 'cooperation:jobopportunitylist' %}">فرصت های شغلی</a></li>
      <li class="uk-active"><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:16px; " href="{% url 'cooperation:createdelegationrequest' %}">درخواست نمایندگی فروش</a></li>
      <li class="uk-active"><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:16px; " href="{% url 'cooperation:createrepairmanrequest' %}">درخواست نمایندگی خدمات</a></li>
  </ul>
</div>
</li>

      <li><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:20px;" class=" " href="{% url 'gallery:gallery' %}">گالری</a></li>
<li><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:20px;" class=" " href="https://sholehkhiz.com/blog/">مقالات</a></li>
    </ul>

</div></div>
        <a class="uk-navbar-item uk-logo" href="{% url 'home' %}"><img src="/media/Logo/logo.png" width="90"></a>
        <div class="uk-navbar-center-right"><a id="humberger" href="#" class="uk-navbar-toggle uk-hidden@m whiteC-text" uk-navbar-toggle-icon uk-toggle="target: #sidenav"></a><div>
    <ul class="uk-navbar-nav">
      <ul class="uk-navbar-nav uk-visible@m">
        <li>
      <a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:20px;; " class="  " href="#">شعله خیز</a>
      <div  class="uk-navbar-dropdown " style="margin-top:-10px; background-color:#ff0a0a;">
          <ul class="uk-nav uk-navbar-dropdown-nav">
            <li class="uk-active"><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:20px;; " href="{% url 'company:about-us' %}">درباره ما</a></li>
              <li class="uk-active"><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:20px;; " href="{% url 'company:complaint' %}">شکایت</a></li>
              <li class="uk-active"><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:20px;; " href="{% url 'company:createfeedback' %}">نظرسنجی</a></li>
              <li class="uk-active"><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:20px;; " href="{% url 'company:contact-us' %}">تماس با ما</a></li>

          </ul>
      </div>
  </li>
        {% if user.is_authenticated and user.is_superuser%}
          <li><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:20px;" class=" " href="{% url 'accounts:superuserdashboard' %}">داشبورد</a></li>
          {% endif %}
        {% if user.is_authenticated %}
        <li><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:20px;" class=" " href="{% url 'logout' %}">خروج</a></li>
        {% if user.is_commonuser %}
        <li><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:20px;" class=" " href="{% url 'commonuser:profile' user.slug %}">پروفایل</a></li>
        {% endif %}
        {% else %}
          <li><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:20px;" class=" " href="{% url 'accounts:login' %}">ورود</a></li>
          <li><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:20px;" class=" " href="{% url 'commonuser:signup' %}">عضویت</a></li>
          {% endif %}
          <li><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:20px;" class=" " href="{% url 'delegations:publiclist' %}">مراکز خدمات</a></li>


      </ul>

    </ul>
</div></div>

</div>

            </nav>
        </header>

        <div style="z-index:5000" id="sidenav" uk-offcanvas="flip: true" style="background-color:#ff0a0a; box-shadow: 0 15px 17px rgba(0, 0,0, 0.18);" class="uk-offcanvas">
            <div style="background-color:#ff0a0a; box-shadow: 0 15px 17px rgba(0, 0,0, 0.18);" class="uk-offcanvas-bar">
                <ul class="uk-nav">
                  {% if user.is_authenticated and user.is_superuser%}
                    <li><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:17px;;" class=" " href="{% url 'accounts:superuserdashboard' %}">داشبورد</a></li>
                    {% endif %}
                  {% if user.is_authenticated %}
                  <li><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:17px;;" class=" " href="{% url 'logout' %}">خروج</a></li>
                  {% if user.is_commonuser %}
                  <li><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:17px;;" class=" " href="{% url 'commonuser:profile' user.slug %}">پروفایل</a></li>
                  {% endif %}
                  {% else %}
                    <li><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:17px;;" class=" " href="{% url 'accounts:login' %}">ورود</a></li>
                    <li><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:17px;;" class=" " href="{% url 'commonuser:signup' %}">عضویت</a></li>
                    {% endif %}
                    <li><span style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:17px;border-bottom: solid red 1px;">محصولات و سفارش</span></li>
                                    </ul>

                                    <ul>
                                      <li class="uk-active"><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:17px;; " href="{% url 'products:radiatorlist' %}">رادیاتور پنلی</a></li>
                                      <li class="uk-active"><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:17px;; " href="{% url 'products:towerdryerlist' %}">حوله خشک کن</a></li>
                                      <li class="uk-active"><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:17px;; " href="{% url 'products:packagelist' %}">پکیج دیواری</a></li>
                                      <li class="uk-active"><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:17px;; " href="{% url 'products:waterheaterlist' %}">آبگرمکن</a></li>
                                    </ul>
                                    <ul class="uk-nav">
                    <li><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:17px;;" class=" " href="{% url 'delegations:publiclist' %}">مراکز خدمات</a></li>
                    <li><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:17px;;" class=" " href="https://sholehkhiz.com/blog/">مقالات</a></li>

                    <li class="uk-active"><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:17px;; " href="{% url 'company:contact-us' %}">تماس با ما</a></li>
                    <li class="uk-active"><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:17px;; " href="{% url 'company:complaint' %}">شکایت</a></li>
                    <li class="uk-active"><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:17px;; " href="{% url 'company:createfeedback' %}">نظرسنجی</a></li>
                    <li class="uk-active"><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:17px;; " href="{% url 'company:about-us' %}">درباره ما</a></li>




                  <li><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:17px;;" class=" " href="{% url 'gallery:gallery' %}">گالری</a></li>
            <li><span style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:17px;border-bottom: solid red 1px;">همکاری</span></li>
                </ul>
                <ul >
                    <li class="uk-active"><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:17px;; " href="{% url 'cooperation:jobopportunitylist' %}">فرصت های شغلی</a></li>
                    <li class="uk-active"><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:17px;; " href="{% url 'cooperation:createdelegationrequest' %}">درخواست نمایندگی فروش</a></li>
                    <li class="uk-active"><a style="color:#ffffff; font-family: 'Yekan', sans-serif; font-size:17px;; " href="{% url 'cooperation:createrepairmanrequest' %}">درخواست نمایندگی خدمات</a></li>
                </ul>
            </div>
        </div>
<br><br><br><br>
      {% block body_block %}
      {% endblock %}
      <footer style="padding:50px;font-size:17px;" class="redC">
        <div  class="uk-grid uk-grid-small uk-child-width-1-2 uk-child-width-1-4@s fHarmattan" uk-grid>
          <div class="uk-text-">
        <a href="{% url 'company:about-us' %}" class="whiteC-text">درباره ما</a><br>
        <a href="{% url 'company:contact-us' %}" class="whiteC-text">تماس با ما</a><br>
        <a href="{% url 'cooperation:jobopportunitylist' %}" class="whiteC-text">فرصت های شغلی</a><br>
        <a href="{% url 'cooperation:createdelegationrequest' %}" class="whiteC-text">درخواست نمایندگی فروش</a><br>
        <a href="{% url 'cooperation:createrepairmanrequest' %}" class="whiteC-text">درخواست نمایندگی خدمات</a><br>
          </div>
          <div class="uk-text-=">
            <a href="{% url 'products:packagelist' %}" class="whiteC-text">پکیج</a><br>
            <a href="{% url 'products:radiatorlist' %}" class="whiteC-text">رادیاتور پنلی</a><br>
            <a href="{% url 'products:waterheaterlist' %}" class="whiteC-text">آبگرمکن</a><br>
            <a href="{% url 'products:towerdryerlist' %}" class="whiteC-text">حوله خشک کن</a><br>
        <a href="{% url 'gallery:gallery' %}" class="whiteC-text">گالری</a><br>
          </div>
          <div class="uk-text-">
            {% if user.is_authenticated %}
              <a href="{% url 'logout' %}" class="whiteC-text">خروج</a><br>
            {% else %}
              <a href="{% url 'accounts:login' %}" class="whiteC-text">ورود</a><br>
              {% endif %}
        <a href="{% url 'commonuser:signup' %}" class="whiteC-text">عضویت</a><br>
        <a href="{% url 'delegations:publiclist' %}" class="whiteC-text">مراکز خدمات</a><br>
        <a href="https://sholehkhiz.com/blog/" class="whiteC-text">مقالات</a><br>
        <a href="{% url 'company:complaint' %}" class="whiteC-text">شکایت</a><br>
          </div>
          <div class="uk-text-center">
            <a class="uk-navbar-item uk-logo" href="{% url 'home' %}"><img src="/media/Logo/logo.png" width="110"></a><br>
            <a href="https://t.me/sholehkhizco/" class="whiteC-text"> <img width="30" src="/media/Logo/telegram.png" alt=""></a>
            <a href="https://www.instagram.com/sholehkhizazar/" class="whiteC-text"><img width="30" src="/media/Logo/instagram.png" alt=""></a>
<a href="https://wa.me/+989146601009" class="redC-text"> <img width="30" src="/media/Logo/watsapp.png" alt=""></a>
          </div>
        </div>

        </div>



</footer>
<div class=" darkgreyC-text fHarmattan uk-text-center" style=" padding-right:5%;font-size:14px;">
  تمام حقوق تحت شرکت شعله خیز آذر محفوظ است.
</div>

</span>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <script type="text/javascript">
      $('#humberger').click(function() {
  $('#sidenav').css({
      'z-index': '5000',
  });
});
      </script>
      {% block script_block %}
      {% endblock %}
    </body>
  </html>