chat/urls.py
from django.urls import include, path
from chat.views import (CreateChatSessionView, ChattingView, PendingChatSessionListView,
                        ActivateChatSessionView, SendMessage, GetUserMessage,
                        CheckActivity, DeleteChatSessionView)

app_name ='chat'
urlpatterns = [
    path('create-chat/', CreateChatSessionView, name='createchatsession'),
    path('chatting/<int:pk>/', ChattingView, name='chatting'),
    path('pending-chats/', PendingChatSessionListView, name='pendingchatsessionlist'),
    path('activate-chat/<int:pk>/', ActivateChatSessionView, name='activatechat'),
    path('send-message/<int:pk>/', SendMessage, name='sendmessage'),
    path('get-user-message/<int:pk>/', GetUserMessage, name='getusermessage'),
    path('check-activity/<int:pk>/', CheckActivity, name='checkactivity'),
    path('delete-session/<int:pk>/', DeleteChatSessionView, name='deletechatsession'),

]

products/urls.py
from django.urls import include, path
from products.views import (CreateProductView, ProductsListViewSuperUser,
                            ProductsDeleteView, ProductsUpdateView,
                            TowerDryerListView, PackageListView,
                            RadiatorListView, WaterHeaterListView)

app_name ='products'
urlpatterns = [
    path('create/', CreateProductView, name='create'),
    path('list-superuser/', ProductsListViewSuperUser, name='listsuperuser'),
    path('delete/<int:pk>/', ProductsDeleteView, name='delete'),
    path('update/<int:pk>/', ProductsUpdateView, name='update'),
    path('towerdryer-list/', TowerDryerListView, name='towerdryerlist'),
    path('package-list/', PackageListView, name='packagelist'),
    path('radiator-list/', RadiatorListView, name='radiatorlist'),
    path('waterheater-list/', WaterHeaterListView, name='waterheaterlist'),

]

templates/home.html
{% extends "BaseTemplates/base2.html" %}

{% block head_block %}
 <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<meta name=”robots” content=”noindex,follow”>
<title>
شعله خیز | تولید کننده ی محصولات گرمایشی
</title>
{% endblock %}

{% block body_block %}

<a style="position:fixed; bottom:20px; right:20px;  -webkit-filter: drop-shadow(5px 5px 10px #222 );filter: ;z-index:511;drop-shadow(5px 5px 10px #222);" target="_blank" href="{% url 'chat:createchatsession' %}">
<img src="/media/Logo/chat.png" width="50" alt="">
  </a>

<!-- Intro Section  ***********************************************************************************  -->
<div >

  <br>
<div class="" style="margin-left: auto;margin-right: auto; max-width:1380px;">


<div style="margin-left: 10%;margin-right: 10%;"  class="uk-position-relative uk-visible-toggle uk-light" tabindex="-1"  uk-slideshow="autoplay: true;autoplay-interval: 5000;">

    <ul class="uk-slideshow-items">

        <li>
            <img src="/media/homepage/2.jpg" alt="عکس رادیاتوز شعله خیز آذر ۲" uk-cover>
        </li>
        <li>
            <img src="/media/homepage/4.jpg" alt="عکس رادیاتوز شعله خیز آذر ۴" uk-cover>
        </li>
    </ul>

    <a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous uk-slideshow-item="previous"></a>
    <a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next uk-slideshow-item="next"></a>

</div>
</div>
</div>
<br>
 <!-- PRODUCTS Section  ***********************************************************************************  -->
 <section style="background-color: #FFFFFF;" class="whiteC">

 <br>
 <h1 id="products" class="uk-h1 tm-heading-fragment fHarmattan redC-text uk-text-center fYekan-bold font-7" style="font-family: Yekan;">محصولات و سفارش</h1>

<div style="padding:4%" class="uk-grid-match uk-text-center uk-grid-small" uk-grid>
<div class="uk-width-1-2 uk-width-1-4@m uk-block fHarmattan uk-text-center">
  <div uk-scrollspy="cls: uk-animation-kenburns;cls: uk-animation-slide-top-medium; repeat: true; delay:450;" ><a href="{% url 'products:radiatorlist' %}">
    <div class="uk-overflow-hidden" >
        <img src="/media/Logo/newradiator.jpg" >
    </div>
</a>
<h2 class="uk-text-top fHarmattan redC-text" style="z-index:50; margin-top:-5%; font-size:20px;" >رادیاتور پنلی</h2>
</div>

    </div>
    <div class="uk-width-1-2 uk-width-1-4@m  uk-block fHarmattan uk-text-center">
      <div uk-scrollspy="cls: uk-animation-kenburns;cls: uk-animation-slide-top-medium; repeat: true; delay:450;"><a href="{% url 'products:packagelist' %}">
        <div class="uk-overflow-hidden">
            <img src="/media/Logo/package.jpeg" >
        </div>
        </a>
        <h2 class="uk-text-top fHarmattan redC-text" style="z-index:50; margin-top:-5%;font-size:20px;">پکیج</h2>
    </div>

</div>
      <div class="uk-width-1-2 uk-width-1-4@m uk-block fHarmattan uk-text-center">
        <div uk-scrollspy="cls: uk-animation-kenburns;cls: uk-animation-slide-top-medium; repeat: true; delay:450;"><a href="{% url 'products:waterheaterlist' %}">
          <div class="uk-overflow-hidden">
              <img src="/media/Logo/waterheater2.jpeg">
          </div></a>
          <h2 class="uk-text-top fHarmattan redC-text" style="z-index:50; margin-top:-5%;font-size:20px;">آبگرمکن</h2>
      </div>

</div>
        <div class="uk-width-1-2 uk-width-1-4@m uk-block fHarmattan uk-text-center">
          <div uk-scrollspy="cls: uk-animation-kenburns;cls: uk-animation-slide-top-medium; repeat: true; delay:450;"><a href="{% url 'products:towerdryerlist' %}">
            <div class="uk-overflow-hidden">
                <img src="/media/Logo/toweldryer2.jpg">
            </div></a>
            <h2 class="uk-text-top fHarmattan redC-text" style="z-index:50; margin-top:-5%;font-size:20px;">حوله خشک کن</h2>
        </div>

</div>
  </div>
  <br>
  <br>
 </section>


 <!-- AboutUs Section  ***********************************************************************************  -->
 <section class="whiteC">

<p style="padding:20px;" class="redC font-7 tm-heading-fragment uk-text-center whiteC-text fHarmattan">شعله خیز گرما بخش خانه ی شما</p>
<img uk-scrollspy="cls: uk-animation-fade; repeat: true; delay:450;" class="uk-visible@s uk-align-center border-radius-4 shadow-2" data-src="/media/homepage/factory_landscape.jpeg" width="70%"    alt="شرکت شعله خیز آذر" uk-img>

 <div uk-scrollspy="cls: uk-animation-fade; repeat: true; delay:450;" class="uk-hidden@s uk-background-cover uk-height-large" href="" style="background-image: url(/media/homepage/factory_square.jpeg);">
 </div>

<br>
   <h1 id="aboutus" class="uk-h1 tm-heading-fragment uk-text-center redC-text fYekan-bold font-7">معرفی شرکت</h1>
  <div class="uk-container">

 <p class="blackC-text fHarmattan uk-text-justify" style="font-size:18px;">
     گروه صنعتی شعله خیز آذر با هدف انتقال جدیدترین تکنولوژی روز دنیا و در راستای تعهد به پیشرفت صنعت ملی در حوزه محصولات گرمایشی، حرکت به سوی تولید محصول رادیاتور پنلی با نام شعله خیز آذر را در منطقه شمال غرب کشور آغاز کرد .

این شرکت در فرصت کوتاه یکساله موفق شد به همت جمعی از جوانان کوشا و متخصص بومی، محصول رادیاتور پنلی را با کیفیت بالا و متفاوت وارد چرخه تولیدات صنعتی داخلی نماید و این آغاز مسیری بود که این شرکت در آن گام نهاد و رفته رفته توانست به مقصد ارزشمند و هدف والای خود کمی نزدیکتر شود.

به امید آنکه رادیاتور پنلی شعله خیز آذر با همان گرمای همانند خورشید فروزانمان ،وارد کانون گرم خانه و خانواده های شما گردد و این حسن انتخاب شما بزرگترین افتخار و دلگرمی برای گروه صنعتی شعله خیز آذر می باشد.
</p>

  </div>
<br>
</section>


 <!-- Delegations Section  ***********************************************************************************  -->


 <div class="uk-grid-match uk-grid-small uk-text-center uk-visible@m" style="background-color:#ebebeb;padding:4%" uk-grid>
   <div class=" uk-width-1-3@s uk-align-center">
     <h1 id="delegations" class="uk-h1 tm-heading-fragment fHarmattan redC-text uk-text-center fYekan-bold font-7">مراکز خدمات</h1>
 <br><br><br>
 <p class="fHarmattan uk-text-justify" style="font-size:18px;">
 تبریز- تهران-  ساری- اردبیل- کرج- یزد- قم- شیراز- مشهد- شهرکرد- سردشت- فولاد شهر- ماکو- کرمانشاه-
  زاهدان- همدان- زنجان- سلماس- رشت- ارومیه- دیوان دره- سنندج- ملایر- شبستر- نور- چالوس- سقز- نوشهر-
  اراک- پیرانشهر- ایلام- بجنورد- قائم شهر- نیشابور- مهاباد- مرودشت- تویسرکان- خرمدره- مریوان- نکا-
  سنقر- آستارا
 </p>
   </div>
       <div class=" uk-width-2-3@s  uk-block ">
         <img src="/media/homepage/iran-map.png" alt="">
   </div>
   </div>
   <div class="uk-grid-match uk-grid-small uk-text-center uk-align-center uk-hidden@m" style="background-color:#ebebeb;padding:4%">

       <h1 id="delegations" class="uk-h1 tm-heading-fragment fHarmattan redC-text uk-align-center uk-text-center fYekan-bold font-7">مراکز خدمات</h1>
   <br>
  <p class="fHarmattan uk-text-justify" style="font-size:18px;">
  تبریز- تهران-  ساری- اردبیل- کرج- یزد- قم- شیراز- مشهد- شهرکرد- سردشت- فولاد شهر- ماکو- کرمانشاه-
   زاهدان- همدان- زنجان- سلماس- رشت- ارومیه- دیوان دره- سنندج- ملایر- شبستر- نور- چالوس- سقز- نوشهر-
   اراک- پیرانشهر- ایلام- بجنورد- قائم شهر- نیشابور- مهاباد- مرودشت- تویسرکان- خرمدره- مریوان- نکا-
   سنقر- آستارا
  </p>

           <img src="/media/homepage/iran-map.png" width="100%" height="100%" alt="">
     </div>





    {% endblock %}
    {% block script_block %}
    <script type="text/javascript">
      var spyNav = UIkit.scrollspyNav('#sidenav', {closest: 'li', scroll: true, offset:170, cls:'uk-active'});
    </script>
    {% endblock %}